### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by hassanrehman01398** [dxue2012/python-webcam-flask#6]
I am getting error while running code locally.Error is of this type.
 Traceback (most recent call last):
7:47:54 PM web.1 |    File "D:\Anaconda\lib\runpy.py", line 193, in _run_module_as_main
7:47:54 PM web.1 |      "__main__", mod_spec)
7:47:54 PM web.1 |    File "D:\Anaconda\lib\runpy.py", line 85, in _run_code
7:47:54 PM web.1 |      exec(code, run_globals)
7:47:54 PM web.1 |    File "C:\Users\hp\Desktop\flask-video-streaming\venv\Scripts\gunicorn.exe\__main__.py", line 5, in <module>
7:47:54 PM web.1 |    File "c:\users\hp\desktop\flask-video-streaming\venv\lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
7:47:54 PM web.1 |      from gunicorn.app.base import Application
7:47:54 PM web.1 |    File "c:\users\hp\desktop\flask-video-streaming\venv\lib\site-packages\gunicorn\app\base.py", line 11, in <module>
7:47:54 PM web.1 |      from gunicorn import util
7:47:54 PM web.1 |    File "c:\users\hp\desktop\flask-video-streaming\venv\lib\site-packages\gunicorn\util.py", line 9, in <module>
7:47:54 PM web.1 |      import fcntl
7:47:54 PM web.1 |  ModuleNotFoundError: No module named 'fcntl'
[DONE] Killing all processes with signal  SIGINT
7:47:54 PM web.1 Exited with exit code null

**Comment by dodiameer** [comment]
You're trying to use gunicorn with windows, but gunicorn doesn't support windows. Try running this on a Mac or Linux system.

**Comment by hassanrehman01398** [comment]
I tried this using linux
